export const UPDATE_TOKEN_INFO = 'UPDATE_TOKEN_INFO';
export const UPDATE_PAGE_STATUS = 'UPDATE_PAGE_STATUS';
export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS';

export const SAVE_ADR_REPORT = 'SAVE_ADR_REPORT';
export const SAVE_ADR_REPORT_SUCCESSFUL = 'SAVE_ADR_REPORT_SUCCESSFUL';
export const SAVE_ADR_REPORT_FAILED = 'SAVE_ADR_REPORT_FAILED';

export const SAMPLE_ACTION = 'SAMPLE_ACTION';
